name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v4
      - uses: tinfoilsh/pri-build-action@main
        with:
          model: deepseek-r1:70b
          domain: inference.delta.tinfoil.sh
          github-token: ${{ secrets.GITHUB_TOKEN }}
